/**
<<<<<<< HEAD
 * WordPress Dependencies
 */
const defaultConfig = require('@wordpress/scripts/config/webpack.config');
const path = require('path');

/**
 * Custom webpack configuration
 *
 * This extends @wordpress/scripts default config to support multiple entry points
 * for different admin pages and frontend components.
 */
module.exports = {
	...defaultConfig,
	entry: {
		// Admin scripts
		'admin': path.resolve(process.cwd(), 'src/admin', 'index.js'),
		'dashboard': path.resolve(process.cwd(), 'src/admin', 'dashboard.js'),
		'settings': path.resolve(process.cwd(), 'src/admin', 'settings.js'),
		'meta-box': path.resolve(process.cwd(), 'src/admin/meta-box', 'index.js'),

		// Frontend scripts
		'frontend': path.resolve(process.cwd(), 'src/frontend', 'index.js'),

		// Styles
		'admin-style': path.resolve(process.cwd(), 'src/admin', 'style.scss'),
		'frontend-style': path.resolve(process.cwd(), 'src/frontend', 'style.scss'),
	},
	output: {
		...defaultConfig.output,
		path: path.resolve(process.cwd(), 'assets/build'),
=======
 * Apprenticeship Connector – Webpack config.
 *
 * Extends @wordpress/scripts defaults with:
 *  - Single admin bundle    (src/admin/App.jsx      → build/admin/index.js)
 *  - Vanilla frontend bundle(src/frontend/index.js  → build/frontend/index.js + index.css)
 *  - Gutenberg blocks       (src/blocks/*\/index.js  → build/blocks/*\/index.js)
 *
 * Block .asset.php files are auto-generated by @wordpress/dependency-extraction-
 * webpack-plugin (included in @wordpress/scripts) and consumed by BlocksLoader.php
 * when calling register_block_type().
 */
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );
const path          = require( 'path' );
const fs            = require( 'fs' );

/**
 * Auto-discover block directories that contain an index.js.
 */
function getBlockEntries() {
	const blocksDir = path.resolve( process.cwd(), 'src/blocks' );

	if ( ! fs.existsSync( blocksDir ) ) {
		return {};
	}

	return fs.readdirSync( blocksDir ).reduce( ( entries, blockName ) => {
		const entryFile = path.join( blocksDir, blockName, 'index.js' );
		if ( fs.existsSync( entryFile ) ) {
			entries[ `blocks/${ blockName }/index` ] = entryFile;
		}
		return entries;
	}, {} );
}

module.exports = {
	...defaultConfig,

	entry: {
		// React admin app
		'admin/index': path.resolve( process.cwd(), 'src/admin', 'App.jsx' ),

		// Vanilla frontend bundle (search filters, expiry countdowns, lazy images)
		'frontend/index': path.resolve( process.cwd(), 'src/frontend', 'index.js' ),

		// Auto-discovered Gutenberg blocks
		...getBlockEntries(),
	},

	output: {
		...defaultConfig.output,
		path:     path.resolve( process.cwd(), 'build' ),
>>>>>>> origin/main
		filename: '[name].js',
	},
};
